---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 55-gvt-gpu
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
    config:
      ignition:
        version: 3.1.0
      storage:
        files:
          - contents:
              source: >-
                data:text/plain;charset=utf-8;base64,b3B0aW9ucyBpOTE1IGVuYWJsZV9ndnQ9MQo=
            mode: 0644
            overwrite: true
            path: /etc/modprobe.d/gpu-intel.conf
          - contents:
              source: 'data:,kvmgt'
            mode: 0644
            overwrite: true
            path: /etc/modules-load.d/gpu-kvmgt.conf
    kernelArguments:
      - 'intel_iommu=on'