---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates:
      - GPU
      - LiveMigration
    permittedHostDevices:
      pciHostDevices:
      - pciVendorSelector: "10DE:<cardid>"
        resourceName: "nvidia.com/V100"
        externalResourceProvider: false
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
