---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 23-vfio-gpu
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
    config:
      ignition:
        version: 3.1.0
      storage:
        files:
          - contents:
              source: >-
                data:text/plain;charset=utf-8;base64,<putyourcardbase64signaturehere>
            mode: 420
            overwrite: true
            path: /etc/modprobe.d/gpu-vfio.conf
          - contents:
              source: 'data:,vfio-pci'
            mode: 420
            overwrite: true
            path: /etc/modules-load.d/gpu-vfio.conf
    kernelArguments:
      - 'intel_iommu=on'
